#!/usr/bin/env bash
# gen-opcodes.sh - regenerate src/cbc_opcodes.inc from the reference jerryscript
# source, version-accurately, using jerryscript's own X-macro opcode list.
#
# how it works: byte-code.h defines CBC_OPCODE_LIST / CBC_EXT_OPCODE_LIST as
# X-macros. we redefine CBC_OPCODE to emit one table row per opcode (index ==
# opcode value, since jerryscript indexes cbc_flags[]/cbc_names[] the same way).
# the 4th macro arg (VM_OC_*) is unused by our emitter, so it is never expanded
# and pulls in no engine dependencies.
set -euo pipefail
cd "$(dirname "$0")/.."

BC="reference/jerryscript/jerry-core/parser/js/byte-code.h"
OUT="src/cbc_opcodes.inc"
[ -f "$BC" ] || { echo "reference source missing: $BC (run 'make corpus' first)"; exit 1; }

mkdir -p reference/build
# the macro-only region: arg-flag defines, branch group helpers, and both lists.
# starts at the first clean #define (CBC_STACK_ADJUST_BASE), ends at CBC_EXT_END.
START=$(grep -n '#define CBC_STACK_ADJUST_BASE' "$BC" | head -1 | cut -d: -f1)
END=$(grep -n 'CBC_OPCODE (CBC_EXT_END' "$BC" | head -1 | cut -d: -f1)
sed -n "${START},${END}p" "$BC" > reference/build/opcode_region.inc

cat > reference/build/gen_opcodes.c <<'EOF'
#include <stdio.h>
#include "opcode_region.inc"
int main(void) {
  int idx;
  printf("/* auto-generated by reference/gen-opcodes.sh from jerryscript byte-code.h */\n");
  printf("/* snapshot version 70. do not edit by hand. */\n\n");
  printf("static const cbc_op_t cbc_ops[] = {\n"); idx = 0;
#define CBC_OPCODE(name, flags, stack, vmoc) printf("  { 0x%02x, \"%s\", 0x%02x, %d },\n", idx++, #name, (unsigned)(flags), (stack));
  CBC_OPCODE_LIST
#undef CBC_OPCODE
  printf("};\n\n");
  printf("static const cbc_op_t cbc_ext_ops[] = {\n"); idx = 0;
#define CBC_OPCODE(name, flags, stack, vmoc) printf("  { 0x%02x, \"%s\", 0x%02x, %d },\n", idx++, #name, (unsigned)(flags), (stack));
  CBC_EXT_OPCODE_LIST
#undef CBC_OPCODE
  printf("};\n");
  return 0;
}
EOF

cc -o reference/build/gen_opcodes reference/build/gen_opcodes.c
{
  echo '/* cbc opcode table type */'
  echo 'typedef struct { unsigned char op; const char *name; unsigned char flags; signed char stack; } cbc_op_t;'
  echo
  ./reference/build/gen_opcodes
} > "$OUT"
echo "wrote $OUT ($(grep -c '{ 0x' "$OUT") opcodes)"
