#!/usr/bin/env bash
# gen-opcodes.sh - regenerate a version-accurate CBC opcode table from a
# jerryscript source tree, using jerryscript's own X-macro opcode list.
#
# usage: gen-opcodes.sh <jerry_src_dir> <suffix> <out_inc>
#   e.g. gen-opcodes.sh reference/jerryscript v70 src/cbc_opcodes_v70.inc
#
# emits `cbc_ops_<suffix>[]` and `cbc_ext_ops_<suffix>[]` (no typedef; main.c
# defines cbc_op_t once). index == opcode value, matching jerryscript's own
# cbc_flags[]/cbc_names[] indexing. the 4th macro arg (VM_OC_*) is unused by the
# emitter, so it is never expanded and pulls in no engine dependencies.
set -euo pipefail
cd "$(dirname "$0")/.."

SRC="${1:?jerry src dir}"
SUF="${2:?suffix, e.g. v70}"
OUT="${3:?output .inc path}"

BC="$SRC/jerry-core/parser/js/byte-code.h"
[ -f "$BC" ] || { echo "reference source missing: $BC"; exit 1; }

# optional 4th arg: newline-separated feature #defines to match the build config
# (older jerry gates opcodes behind #if ENABLED(JERRY_ESNEXT) etc., so the opcode
# numbering is config-dependent and must match the snapshots being analysed).
DEFS="${4:-}"

WORK="reference/build/$SUF"
mkdir -p "$WORK"
START=$(grep -n '#define CBC_STACK_ADJUST_BASE' "$BC" | head -1 | cut -d: -f1)
# CBC_EXT_END may span several backslash-continued lines; take the whole macro.
ENDSTART=$(grep -n 'CBC_OPCODE (CBC_EXT_END' "$BC" | head -1 | cut -d: -f1)
END=$(awk -v s="$ENDSTART" 'NR>=s { if ($0 !~ /\\[ \t]*$/) { print NR; exit } }' "$BC")
sed -n "${START},${END}p" "$BC" > "$WORK/opcode_region.inc"

# feature macros used by the opcode region's #if guards
printf '#define ENABLED(FEATURE) ((FEATURE) == 1)\n%s\n' "$DEFS" > "$WORK/gen_defines.h"

cat > "$WORK/gen_opcodes.c" <<EOF
#include <stdio.h>
#include "gen_defines.h"
#include "opcode_region.inc"
int main(void) {
  int idx;
  printf("/* auto-generated by reference/gen-opcodes.sh from jerryscript byte-code.h ($SUF) */\n");
  printf("/* do not edit by hand. */\n\n");
  printf("static const cbc_op_t cbc_ops_$SUF[] = {\n"); idx = 0;
#define CBC_OPCODE(name, flags, stack, vmoc) printf("  { 0x%02x, \"%s\", 0x%02x, %d },\n", idx++, #name, (unsigned)(flags), (stack));
  CBC_OPCODE_LIST
#undef CBC_OPCODE
  printf("};\n\n");
  printf("static const cbc_op_t cbc_ext_ops_$SUF[] = {\n"); idx = 0;
#define CBC_OPCODE(name, flags, stack, vmoc) printf("  { 0x%02x, \"%s\", 0x%02x, %d },\n", idx++, #name, (unsigned)(flags), (stack));
  CBC_EXT_OPCODE_LIST
#undef CBC_OPCODE
  printf("};\n");
  return 0;
}
EOF

cc -o "$WORK/gen_opcodes" "$WORK/gen_opcodes.c"
"$WORK/gen_opcodes" > "$OUT"
echo "wrote $OUT ($(grep -c '{ 0x' "$OUT") opcodes for $SUF)"
